---
include:
  - board: nice_nano
    shield: mini_keyboard
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_BUILD_OUTPUT_UF2=y
    artifact-name: mini_keyboard_with_studio
